version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd123
      MYSQL_DATABASE: secretsanta_db
    volumes:
      - /var/lib/mysql

  secretsanta:
    image: python:3.7
    links:
      - db
    env_file:
      - .env
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - .:/secretsanta
    restart: always
    environment:
      FLASK_ENV: "development"
    command: >
      bash -c "cd /secretsanta && 
      pip install -r requirements.txt && 
      pip install mysqlclient &&  
      flask db upgrade &&  
      flask run --host 0.0.0.0"
