[default]
DEBUG = false
CSRF_ENABLED = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
TITLE = "Secret Santa Bot" 
 
[development]
DEVELOPMENT = true
DEBUG = true
SQLALCHEMY_TRACK_MODIFICATIONS = true
SQLALCHEMY_DATABASE_URI="sqlite:///development.db" 
 
[production]
DEBUG = false 