[default]
DEBUG = false
CSRF_ENABLED = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
TITLE = "Fizz Buzz Bot" 
 
[development]
DEVELOPMENT = true
DEBUG = true
SQLALCHEMY_TRACK_MODIFICATIONS = true
SQLALCHEMY_DATABASE_URI="mysql://root:p@ssw0rd123@db/santasecret" 
 
[production]
DEBUG = false 