[default]
DEBUG = false
CSRF_ENABLED = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
TITLE = "Secret Santa Bot"  
 
[development]
DEVELOPMENT = true
DEBUG = true
SQLALCHEMY_TRACK_MODIFICATIONS = true 
DB_NAME = "development.db"
SQLALCHEMY_DATABASE_URI="@jinja sqlite:///{{ this.DB_NAME | abspath }}"
 
[production]
DEBUG = false 
SQLALCHEMY_DATABASE_URI="mysql://root:p@ssw0rd123@0.0.0.0:3306/secretsanta_db"

[testing]
DEBUG = true 
DB_NAME = "testing.db"
SQLALCHEMY_DATABASE_URI="@jinja sqlite:///{{ this.DB_NAME | abspath }}"