[default]
DEBUG = false
CSRF_ENABLED = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
TITLE = "Flask Secret Santa"  
TWILIO_WHATSAPP = "+15005550006"

[development]
DEVELOPMENT = true
DEBUG = true
SQLALCHEMY_TRACK_MODIFICATIONS = true 
DB_NAME = "development.db"
SQLALCHEMY_DATABASE_URI="@jinja sqlite:///{{ this.DB_NAME | abspath }}"
 
[production]
DEBUG = false 
DB_NAME = "production.db"
SQLALCHEMY_DATABASE_URI="@jinja sqlite:///{{ this.DB_NAME | abspath }}"# "mysql://user:password@0.0.0.0:3306/database"

[testing]
DEBUG = true 
DB_NAME = "testing.db"
SQLALCHEMY_DATABASE_URI="@jinja sqlite:///{{ this.DB_NAME | abspath }}"